# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Chi ha ucciso il Conte?
tagline:          'Design'
description:      'UX/UI Design <br>Digital Fabrication<br> Research'

url:              /
baseurl:         "chihauccisoilconte.eu" # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Nicolò Merendino'
  url:            https://twitter.com/chihauccilconte

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

github:
  repo:             https://github.com/chihauccisoilconte

instagram: https://www.instagram.com/chihauccisoilconte/
facebook:     https://www.facebook.com/ChiHaUccisoIlConte/
email:        mailto:chihauccilconte@gmail.com
linkedin:  https://www.linkedin.com/in/nicolo-merendino/
mastodon:   https://c.im/@chihauccisoilconte

